### ISSUE TITLE
Fusion crashes right after entering the playmode

### ISSUE THREAD

**Issue by rickomax** [LB--/windows-edif#12]
Hey, great working fixing EDIF issues!

Do you have any issues when entering playmode?

Here Fusion crashes right after entering, and it's not even entering
"CreateRunObject" function (I've tried to debug).

Any tips?

**Comment by LB--** [comment]
Which version of Fusion are you using? Does the base template also experience this issue?

**Comment by rickomax** [comment]
Clickteam Fusion Standard 2.5 R289.3 (unicode).
I haven't tested with the base template yet.

**Comment by rickomax** [comment]
Well. I've tested with standard EDIF template, and the game runs just fine.
But if I add my code to that template, it will crash right after entering the runtime mode.
By the way, may be something related to my code (I just cannot find what, as I haven't changed any runtime related code)

**Comment by LB--** [comment]
Which files and functions do you modify to add your code? It's possible some edittime code is crashing in the transition to runtime.

**Comment by rickomax** [comment]
@LB--  I figured out that a variable I was reading from Extension class constructor was not assigned at that point. At the first moment I could not use Visual Studio to debug the issue, but I managed to debug the exception edrt.exe was throwing. Your code is working great, thank you!
